# ESTO ES UN COMENTARIO
# Todo lo que está a la derecha de # es solo para nosotros

version: 0.3.5 # NO TOCAR

# HODL username
username: "ivanbura"

# NOSTR Settings
nostr:
  npub: "npub1vy85w6rvc4v7jcgnsllfk07pnuzyv6zk8gy0xvqxq0y5t9unkwfquyhtn0"

# Configuración Global
html:
# title: Este valor no funciona porque esta comentado
  title: "Ivanbura - Mis perfiles" # Este es el Título que aparece en la pestaña de navegador

# Colores de plantilla
theme:
  background_color: "#f9fafb"
  # cover_color: "#ff7070"

# Configuración Central
main:
  title: "Ivanbura" # Aca podes poner tu nombre o el de tu producto

# Lista de bloques
blocks:
  # Estos bloques los podes editar cambiando SOLO el texto que está en blanco
  # Sacale 

  - title: Instagram
    icon: instagram
    url: https://www.instagram.com/ivan.bura/

  - title: Twitter
    icon: twitter
    url: https://twitter.com/ivanbura
    
  - title: LinkedIn # Este es el nombre del botón
    icon: linkedin # Este es el nombre del icono (si queres añadir una red social nueva, prestá atencion que es todo con minúscula)
    url: https://www.linkedin.com/in/ivan-buraczewski-145b9a28/

  - title: Github
    icon: github
    url: https://github.com/ivanbura

  - title: Iris
    icon: iris
    url: https://iris.to/ivanbura

# - title: Sitio Web
#   icon: url
#   url: https://www.TU-WEB.com

# - title: Telegram
#   icon: telegram
#   url: https://t.me/TU-USUARIO
    
# Guardá el archivo haciendo click en Commit Changes, abajo
# Volvé a las instrucciones
